### ISSUE TITLE
How to backup when the docker-compose is upgraded to version 2 with default network?

### ISSUE THREAD

**Issue by cseetharamu** [istepanov/docker-mongodump#5]
Getting
Failed: error connecting to db server: no reachable servers

**Comment by ghost** [comment]
I am using `docker-mongodump` as a part of a network. Here is my file `docker-compose.yml`:

```
version: '2'

services:

  wekandb:
    image: mongo:3.2.11
    container_name: wekan-db
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - wekan-tier
    expose:
      - 27017
    volumes:
      - /volume1/docker/wekan_mongo_data:/data/db

  wekanapp:
    image: mquandalle/wekan
    container_name: wekan-app
    restart: always
    networks:
      - wekan-tier
    ports:
      - 5200:80
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=http://localhost:5200
    depends_on:
      - wekandb

  wekanbackup:
    image: istepanov/mongodump
    container_name: wekan-backup
    restart: always
    networks:
      - wekan-tier
    environment:
      - CRON_SCHEDULE=0 2 * * *
      - MONGO_PORT_27017_TCP_PORT=27017
      - MONGO_PORT_27017_TCP_ADDR=wekandb
    volumes:
      - /volume1/docker/wekan_mongo_backup:/backup
    depends_on:
      - wekandb

volumes:
  wekan-db:
    driver: local

networks:
  wekan-tier:
    driver: bridge
```

The values for MONGO_PORT_27017_TCP_PORT and MONGO_PORT_27017_TCP_ADDR were empty when I tried to echo them from inside the container, so I had to add them as environment parameters.
